#!/usr/bin/env zsh

cf_nvm_default_nodejs_version=lts/fermium
cf_user_config_init_script_url=https://raw.githubusercontent.com/andis-sprinkis/nix-user-config/master/.local/bin/init_nix_user_config
cf_user_config_init_script_args=--with-nvim-config
