#!/usr/bin/env zsh

cf_default_nodejs_version="18.13.20"
cf_user_config_init_script_url=https://raw.githubusercontent.com/andis-sprinkis/nix-user-config/master/.local/bin/init_nix_user_config
cf_user_config_init_script_args=--with-nvim-config
