#!/usr/bin/env zsh

cf_nvm_default_nodejs_version=lts/fermium
cf_git_url_nix_user_config=https://github.com/andis-sprinkis/nix-user-config
cf_git_url_nvim_user_config=https://github.com/andis-sprinkis/nvim-user-config
