#!/usr/bin/env zsh
set -e
dir=$(cd -P -- "$(dirname -- "$0")" && pwd -P)

print_br_bottom() { echo $1; echo }
print_br_top() { echo; echo $1 }
print_br_both() { echo; echo $1; echo }

fn_call() {
  for fn in "$@"; do
    print_br_bottom "Function $fn has started..."
    $fn
    print_br_bottom "Function $fn has completed!"
  done
}

print_stage_status() {
  [ "$1" -eq "0" ] && print_br_bottom "Starting $2 stage..." 
  [ "$1" -eq "1" ] && print_br_bottom "$2 stage has completed!"
}

install_brew() {
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  echo 'eval $(/opt/homebrew/bin/brew shellenv)' >> /Users/$USER/.zprofile
  eval $(/opt/homebrew/bin/brew shellenv)
}

install_pkg_brew() {
  [ -s $dir/pkg_brew_tap ] && brew tap $(echo $(cat $dir/pkg_brew_tap))
  [ -s $dir/pkg_brew ] && brew install $(echo $(cat $dir/pkg_brew))
  [ -s $dir/pkg_brew_cask ] && brew install --cask $(echo $(cat $dir/pkg_brew_cask))
}

install_user_config() {
  local dir_cfg_git=$HOME/.dotfiles_git
  local temp_path=$(mktemp -d)
  git clone --separate-git-dir=$dir_cfg_git https://github.com/andis-sprinkis/nix-user-config $temp_path
  rsync --recursive --verbose --exclude '.git' $temp_path/ $HOME
  git --git-dir=$dir_cfg_git --work-tree=$HOME config --local status.showUntrackedFiles no
  git --git-dir=$dir_cfg_git --work-tree=$HOME submodule update --init
}

install_nodejs() {
  export VOLTA_HOME="$HOME/.volta"
  PATH="$VOLTA_HOME/bin:$PATH"
  volta install "node@18.13.20"
}

install_pkg_npm() {
  [ -s $dir/pkg_npm ] && volta install $(echo $(cat $dir/pkg_npm))
}

stage_install_brew() {
  stage="Installing brew"
  print_stage_status 0 "$stage"

  fn_call "install_brew"

  print_stage_status 1 "$stage"
}

stage_post_install_brew() {
  stage="Installing user packages and configuration"
  print_stage_status 0 "$stage"

  fn_call "install_pkg_brew"
  fn_call "install_user_config"
  fn_call "install_nodejs"
  fn_call "install_pkg_npm"

  print_stage_status 1 "$stage"
}

[ -z "$1" ] || [ "$1" -eq "0" ] && stage_install_brew
[ "$1" ] && [ "$1" -eq "1" ] && stage_post_install_brew
