#!/usr/bin/env zsh
set -e
dir=$(cd -P -- "$(dirname -- "$0")" && pwd -P)
. $dir/util
. $dir/config

install_brew() {
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  echo 'eval $(/opt/homebrew/bin/brew shellenv)' >> /Users/$USER/.zprofile
  eval $(/opt/homebrew/bin/brew shellenv)
}

install_pkg_brew() {
  if [ -s $dir/pkg_brew_tap ]; then
    brew tap $(echo $(cat $dir/pkg_brew_tap))
  fi

  if [ -s $dir/pkg_brew ]; then
    brew install $(echo $(cat $dir/pkg_brew))
  fi

  if [ -s $dir/pkg_brew_cask ]; then
    brew install --cask $(echo $(cat $dir/pkg_brew_cask))
  fi
}

install_user_config() {
  if [ "$cf_git_url_nix_user_config" ]; then
    curl -LO $cf_user_config_init_script_url --output $HOME/init_user_config
    chmod +x $HOME/init_user_config
    $HOME/init_user_config "$cf_user_config_init_script_args"
    rm $HOME/init_user_config
  fi
}

install_nodejs() {
  if [ "$cf_nvm_default_nodejs_version" ]; then
    mkdir -p $HOME/.nvm
    export NVM_DIR=$HOME/.nvm
    . $(brew --prefix)/opt/nvm/nvm.sh
    nvm install $cf_nvm_default_nodejs_version
    nvm alias default $cf_nvm_default_nodejs_version
    nvm use default
  fi
}

install_pkg_npm() {
  if [ -s $dir/pkg_npm ]; then
    npm install --global $(echo $(cat $dir/pkg_npm))
  fi
}

stage_install_brew() {
  stage="Installing brew"
  print_stage_status 0 "$stage"

  fn_call "install_brew"

  print_stage_status 1 "$stage"
}

stage_post_install_brew() {
  stage="Installing user packages and configuration"
  print_stage_status 0 "$stage"

  fn_call "install_pkg_brew"
  fn_call "install_user_config"
  fn_call "install_nodejs"
  fn_call "install_pkg_npm"

  print_stage_status 1 "$stage"
}

[ -z "$1" ] || [ "$1" -eq "0" ] && stage_install_brew
[ "$1" ] && [ "$1" -eq "1" ] && stage_post_install_brew
