#!/usr/bin/env zsh
# TODO: 
# - add disable system animations commands
# - store and load iterm2:
#  - config
#  - color scheme
set -e
echo_br_bottom() { echo $1; echo; }
echo_br_top() { echo; echo $1 }
echo_br_both() { echo; echo $1; echo }
echo_fn_status() {
  if [ "$1" -eq "0" ]; then; echo_br_bottom "Function $2 started..."; fi 
  if [ "$1" -eq "1" ]; then; echo_br_bottom "Function $2 is complete!"; fi 
}
echo_script_status() {
  if [ "$1" -eq "0" ]; then; echo_br_bottom "Starting $2..."; fi 
  if [ "$1" -eq "1" ]; then; echo_br_bottom "$2 is complete!"; fi 
}

scriptname="macOS user session configuration script"
echo_script_status 0 "$scriptname"

install_brew() {
  echo_fn_status 0 $funcstack[1]

  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

  echo_fn_status 1 $funcstack[1]
}

install_brew_pkg() {
  echo_fn_status 0 $funcstack[1]

  brew install \
    wget \
    bat \
    tree \
    coreutils \
    findutils \
    gnu-tar \
    gnu-sed \
    gawk \
    gnutls \
    gnu-indent \
    gnu-getopt \
    grep \
    ripgrep \
    lf \
    fzf \
    zsh-syntax-highlighting \
    git \
    neovim \
    nvm \
    atool \
    python3 \
    unzip \
    tldr

    brew tap homebrew/cask-fonts

    brew install --cask \
      iterm2 \
      keepassxc \
      font-cascadia-code \
      font-cascadia-code-pl \
      font-cascadia-mono \
      font-cascadia-mono-pl

  echo_fn_status 1 $funcstack[1]
}

install_zsh_session_config() {
  echo_fn_status 0 $funcstack[1]

  wget --no-cache -P $HOME/ https://raw.githubusercontent.com/andis-sprinkis/linux-user-config/master/.zshrc
  if [ -f $HOME/.zshrc.1 ]; then
    rm $HOME/.zshrc
    mv $HOME/.zshrc.1 $HOME/.zshrc
  fi

  echo_fn_status 1 $funcstack[1]
}

install_node_lts() {
  echo_fn_status 0 $funcstack[1]

  mkdir -p $HOME/.nvm
  export NVM_DIR=$HOME/.nvm
  . $(brew --prefix)/opt/nvm/nvm.sh
  nvm install lts/fermium
  nvm alias default lts/fermium
  nvm use default

  echo_fn_status 1 $funcstack[1]
}

install_node_pkg() {
  echo_fn_status 0 $funcstack[1]

  npm install --global yarn

  echo_fn_status 1 $funcstack[1]
}

install_nvim_config() {
  echo_fn_status 0 $funcstack[1]

  mkdir -p $HOME/.config
  [ -d $HOME/.config/nvim ] && rm -rf $HOME/.config/nvim
  git clone https://github.com/andis-sprinkis/neovim-user-config $HOME/.config/nvim

  echo_fn_status 1 $funcstack[1]
}

setup() {
  install_brew
  install_brew_pkg
  install_zsh_session_config
  install_node_lts
  install_node_pkg
  install_nvim_config
}

setup
echo_script_status 1 "$scriptname"
