#!/usr/bin/env zsh
# TODO: 
# - add disable system animations commands
# - store and load iterm2:
#  - config
#  - color scheme
set -e
echo_br_bottom() { echo $1; echo; }
echo_br_top() { echo; echo $1 }
echo_br_both() { echo; echo $1; echo }
echo_fn_status() {
  if [ "$1" -eq "0" ]; then; echo_br_bottom "Function $2 started..."; fi 
  if [ "$1" -eq "1" ]; then; echo_br_bottom "Function $2 is complete!"; fi 
}
echo_script_status() {
  if [ "$1" -eq "0" ]; then; echo_br_bottom "Starting $2..."; fi 
  if [ "$1" -eq "1" ]; then; echo_br_bottom "$2 is complete!"; fi 
}

scriptname="macOS user session configuration script"
echo_script_status 0 "$scriptname"

install_brew() {
  echo_fn_status 0 $funcstack[1]

  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

  echo_fn_status 1 $funcstack[1]
}

install_brew_pkg() {
  echo_fn_status 0 $funcstack[1]

  brew install \
    atool \
    bat \
    coreutils \
    fd \
    findutils \
    fzf \
    gawk \
    git \
    gnu-getopt \
    gnu-indent \
    gnu-sed \
    gnu-tar \
    gnutls \
    grep \
    lf \
    neovim \
    nvm \
    python3 \
    ripgrep \
    sd \
    tldr
    tree \
    unzip \
    wget \
    zsh-syntax-highlighting \

  brew tap homebrew/cask-fonts

  brew install --cask \
    font-cascadia-code \
    font-cascadia-code-pl \
    font-cascadia-mono \
    font-cascadia-mono-pl
    iterm2 \
    keepassxc \

  echo_fn_status 1 $funcstack[1]
}

install_nix_user_config() {
  echo_fn_status 0 $funcstack[1]

  temp_path=$(mktemp -d)
  git clone --separate-git-dir=$HOME/.dotfiles-git https://github.com/andis-sprinkis/nix-user-config $temp_path
  rsync --recursive --verbose --exclude '.git' $temp_path/ $HOME
  git --git-dir=$HOME/.dotfiles-git/ --work-tree=$HOME config --local status.showUntrackedFiles no
  git --git-dir=$HOME/.dotfiles-git/ --work-tree=$HOME submodule update --init

  echo_fn_status 1 $funcstack[1]
}

install_node_lts() {
  echo_fn_status 0 $funcstack[1]

  mkdir -p $HOME/.nvm
  export NVM_DIR=$HOME/.nvm
  . $(brew --prefix)/opt/nvm/nvm.sh
  nvm install lts/fermium
  nvm alias default lts/fermium
  nvm use default

  echo_fn_status 1 $funcstack[1]
}

install_node_pkg() {
  echo_fn_status 0 $funcstack[1]

  npm install --global yarn

  echo_fn_status 1 $funcstack[1]
}

setup() {
  install_brew
  install_brew_pkg
  install_nix_user_config
  install_node_lts
  install_node_pkg
}

setup
echo_script_status 1 "$scriptname"
