#!/usr/bin/env sh
set -eu

echo "
brew upgrade:
"
brew update

# ------------------------------------------------------------------------------

echo "
brew packages upgrade:
"
brew upgrade

# ------------------------------------------------------------------------------

[ -s "./pkg_brew_tap" ] && {
  echo "
Install brew tap:
"
  brew tap $(echo $(cat "./pkg_brew_tap"))
}

# ------------------------------------------------------------------------------

[ -s "./pkg_brew" ] && {
  echo "
Install brew packages:
"
  brew install $(echo $(cat "./pkg_brew"))
}

# ------------------------------------------------------------------------------

[ -s "./pkg_brew_cask" ] && {
  echo "
Install brew cask:
"
  brew install --cask $(echo $(cat "./pkg_brew_cask"))
}

# ------------------------------------------------------------------------------
#
[ -s "./pkg_pypi" ] && {
  echo "
PyPI packages upgrade:
"
  pipx upgrade-all

  echo "
PyPI packages installation:
"
  for p in $(echo $(cat "./pkg_pypi")); do pipx install $p; done
}

# ------------------------------------------------------------------------------

[ -s "./pkg_npm" ] && {
  echo "
npm packages installation:
"
  volta install $(echo $(cat "./pkg_npm"))
}
