#!/usr/bin/env zsh

# Pad echo output with line breaks

print_br_bottom() {
  echo $1; echo
}

print_br_top() {
  echo; echo $1
}

print_br_both() {
  echo; echo $1; echo
}

# Annotate functions and stages of scripts

fn_call() {
  for fn in "$@"; do
    print_br_bottom "Function $fn has started..."
    $fn
    print_br_bottom "Function $fn has completed!"
  done
}

print_stage_status() {
  if [ "$1" -eq "0" ]; then
    print_br_bottom "Starting $2 stage...";
  fi 

  if [ "$1" -eq "1" ]; then; 
    print_br_bottom "$2 stage has completed!";
  fi 
}
